services:
  web:
    image: lottery
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
    networks:
      - npm

networks:
  npm:
    external: true
